// Code generated by mdatagen. DO NOT EDIT.

package bigqueryexporter

import (
	"testing"

	"go.uber.org/goleak"
)

func TestMain(m *testing.M) {
	// The managedwriter client pulls in opencensus, whose stats view worker
	// starts at package init and runs for the life of the process. It is not
	// a leak this package can close, so it is ignored explicitly rather than
	// by disabling the check.
	goleak.VerifyTestMain(m,
		goleak.IgnoreTopFunction("go.opencensus.io/stats/view.(*worker).start"),
	)
}
