// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("bigquery")
	ScopeName = "github.com/haiyuan-eng-google/BQ-OTEL-Exporter"
)

const (
	TracesStability = component.StabilityLevelDevelopment
	LogsStability   = component.StabilityLevelDevelopment
)
